SUPABASE_URL = https://ovqdhqnlisrylqihohvi.supabase.co
SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cWRocW5saXNyeWxxaWhvaHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NTA3MjEsImV4cCI6MjA3OTAyNjcyMX0.aCiT0O0VeFZf5Vs452nw14Tog3WhBj-pL07NRbPBZoU
